car_loader_memory=150000			# Memory allocated for loading car models (default: 50000)
frame_memory_buffer=13107000		# Memory allocated for rendering objects (default: 409600)
fastmem=12900608			# Memory allocated for the FastMem allocator (default: 2225152)
replacement_texture_table=32767		# Amount of replacement textures, i.e. car lights and license plates (default: 182)
vehicle_count=512			# Amount of vehicles (default: 20)
rigidbody_count=2048			# Amount of physics objects (default: 64)
simplerigidbody_count=2048		# Amount of simple physics objects, i.e. smackables (default: 96)

[slot_pools]
#AnimCtrlSlotPool=64			# default: 64
#Anim_CAnimSkeleton_SlotPool=8		# default: 8
#Anim_CNFSAnimBank_SlotPool=81		# default: 81
#AStarNodeSlotPool=3072			# default: 3072
#AStarSearchSlotPool=16			# default: 16
#AUD_Csis_SlotPools=256			# default: 256
#bFile_System=68			# default: 68
#CACHE__Speech_Event_slotpool=160	# default: 160
CarEmitterPositionSlotPool=65535	# default: 500
CarLoadedRideInfoSlotPool=1024		# default: 40
CarLoadedSkinLayerSlotPool=65535	# default: 1500
CarLoadedSolidPackSlotPool=32767	# default: 60
CarLoadedTexturePackSlotPool=32767	# default: 60
CarPartModelPool=65535			# default: 1024
#ClanSlotPool=40				# default: 40
#eAnimTextureSlotPool=256		# default: 256
#Ecstacy_ModelSlotPool=3700		# default: 3700
#eLightMaterialPlatInfoSlotPool=220	# default: 220
eMeshRender=131070			# default: 4096
#EmitterGroupSlotPool=200		# default: 200
#EmitterSlotPool=500			# default: 500
ePolySlotPool=2048			# default: 32
eStreamingPackSlotPool=1024		# default: 64
eStripSlotPool=2048			# default: 32
#EventHandlerSlotPool=20			# default: 20
EventSlotPool=512			# default: 60
#FERenderEPolySlotPool=840		# default: 840
#FERenderObjectSlotPool=384		# default: 384
#g_textureHeaderPool=1024		# default: 1024
#g_vertexBufferHeaderPool=1024		# default: 1024
ParticleSlotPool=65535			# default: 1024
QueuedFileSlotPool=32767		# default: 200
ResourceFileSlotPool=512		# default: 80
#SampleWrapper_SlotPool=129		# default: 129
#ShadowMapMeshSlotPool=40		# default: 40
#SkidSetSlotPool=128			# default: 128
#SpaceNodeSlotPool=80			# default: 80
#Stitch_SlotPool=45			# default: 45
TexturePackSlotPool=2048		# default: 128
VehicleDamagePartSlotPool=65535		# default: 240
VehiclePartDamageZoneSlotPool=32767	# default: 100
#VoiceActors_slotpool=10			# default: 10
#WorldAnimCtrl_SlotPool=149		# default: 149
#WorldAnimEntityTreeInfo_SlotPool=39	# default: 39
#WorldAnimEntityTree_SlotPool=66		# default: 66
#WorldAnimEntity_SlotPool=213		# default: 213
#WorldAnimInstanceEntry_SlotPool=66	# default: 66
#WorldModelSlotPool=128			# default: 128